services:
  app:
    container_name: hqaudio-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
        mode: host
    volumes:
      - ./logs:/app/logs:z
    environment:
      - PORT=3000
      - RUST_LOG=info
      - REDIS_URL=redis://hqaudio-redis:6379/0
      - TZ=Asia/Kolkata
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - hqaudio-redis

  hqaudio-redis:
    container_name: hqaudio-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
