services:
  app:
    container_name: jiosaavn-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./logs:/app/logs
    environment:
      - PORT=3000
      - RUST_LOG=info
    env_file:
      - .env
    restart: unless-stopped
