name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 45069
          script: |
            # If the old folder exists, rename it to the new name
            if [ -d "$HOME/jiosaavn-api" ]; then
              mv $HOME/jiosaavn-api $HOME/hqaudio-api
            fi
            
            # Clone the repository if it doesn't exist
            if [ ! -d "$HOME/hqaudio-api" ]; then
              git clone https://github.com/suvojeet-sengupta/jiosaavn-api.git $HOME/hqaudio-api
            fi
            
            # Navigate to the project directory on your VPS.
            cd $HOME/hqaudio-api
            
            # Pull the latest changes
            git pull origin main
            
            # Rebuild and restart the application using docker-compose
            docker-compose up -d --build
